version: '3'

volumes:
  database_local:

services:
  hellodjango:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: hellodjango
    container_name: hellodjango
    working_dir: /app
    volumes:
      - database_local:/app/database
      - .:/app
    ports:
      - "8000:8000"
    command: /start.sh